import Foundation

nonisolated enum AppConfig {
    static let EXPO_PUBLIC_PROJECT_ID: String = Config.EXPO_PUBLIC_PROJECT_ID
    static let EXPO_PUBLIC_REVENUECAT_API_KEY: String = Config.EXPO_PUBLIC_REVENUECAT_API_KEY
    static let EXPO_PUBLIC_RORK_API_BASE_URL: String = Config.EXPO_PUBLIC_RORK_API_BASE_URL
    static let EXPO_PUBLIC_RORK_AUTH_URL: String = Config.EXPO_PUBLIC_RORK_AUTH_URL
    static let EXPO_PUBLIC_SUPABASE_ANON_KEY: String = Config.EXPO_PUBLIC_SUPABASE_ANON_KEY
    static let EXPO_PUBLIC_SUPABASE_URL: String = Config.EXPO_PUBLIC_SUPABASE_URL
    static let EXPO_PUBLIC_TEAM_ID: String = Config.EXPO_PUBLIC_TEAM_ID
    static let EXPO_PUBLIC_TOOLKIT_URL: String = Config.EXPO_PUBLIC_TOOLKIT_URL

    static let allValues: [String: String] = [
        "EXPO_PUBLIC_PROJECT_ID": EXPO_PUBLIC_PROJECT_ID,
        "EXPO_PUBLIC_REVENUECAT_API_KEY": EXPO_PUBLIC_REVENUECAT_API_KEY,
        "EXPO_PUBLIC_RORK_API_BASE_URL": EXPO_PUBLIC_RORK_API_BASE_URL,
        "EXPO_PUBLIC_RORK_AUTH_URL": EXPO_PUBLIC_RORK_AUTH_URL,
        "EXPO_PUBLIC_SUPABASE_ANON_KEY": EXPO_PUBLIC_SUPABASE_ANON_KEY,
        "EXPO_PUBLIC_SUPABASE_URL": EXPO_PUBLIC_SUPABASE_URL,
        "EXPO_PUBLIC_TEAM_ID": EXPO_PUBLIC_TEAM_ID,
        "EXPO_PUBLIC_TOOLKIT_URL": EXPO_PUBLIC_TOOLKIT_URL,
    ]
}
